/**
 * PostgreSQL error codes mapped to human-readable names.
 * @see https://www.postgresql.org/docs/current/errcodes-appendix.html
 */
export const postgresErrorCodes: Record<string, string> = {
  '00000': 'successful_completion',
  '01000': 'warning',
  '0100C': 'dynamic_result_sets_returned',
  '01008': 'implicit_zero_bit_padding',
  '01003': 'null_value_eliminated_in_set_function',
  '01007': 'privilege_not_granted',
  '01006': 'privilege_not_revoked',
  '01004': 'string_data_right_truncation',
  '01P01': 'deprecated_feature',
  '02000': 'no_data',
  '08000': 'connection_exception',
  '08003': 'connection_does_not_exist',
  '08006': 'connection_failure',
  '08001': 'sqlclient_unable_to_establish_sqlconnection',
  '08004': 'sqlserver_rejected_establishment_of_sqlconnection',
  '08007': 'transaction_resolution_unknown',
  '08P01': 'protocol_violation',
  '22000': 'data_exception',
  '22012': 'division_by_zero',
  '22003': 'numeric_value_out_of_range',
  '22001': 'string_data_right_truncation',
  '22P02': 'invalid_text_representation',
  '23000': 'integrity_constraint_violation',
  '23001': 'restrict_violation',
  '23502': 'not_null_violation',
  '23503': 'foreign_key_violation',
  '23505': 'unique_violation',
  '23514': 'check_violation',
  '23P01': 'exclusion_violation',
  '25000': 'invalid_transaction_state',
  '25P02': 'in_failed_sql_transaction',
  '40000': 'transaction_rollback',
  '40001': 'serialization_failure',
  '40P01': 'deadlock_detected',
  '42000': 'syntax_error_or_access_rule_violation',
  '42601': 'syntax_error',
  '42501': 'insufficient_privilege',
  '42703': 'undefined_column',
  '42883': 'undefined_function',
  '42P01': 'undefined_table',
  '42701': 'duplicate_column',
  '42P07': 'duplicate_table',
  '53000': 'insufficient_resources',
  '53100': 'disk_full',
  '53200': 'out_of_memory',
  '53300': 'too_many_connections',
  '57014': 'query_canceled',
  '57P01': 'admin_shutdown',
  '58000': 'system_error',
  P0001: 'raise_exception',
  P0002: 'no_data_found',
  XX000: 'internal_error',
  XX001: 'data_corrupted',
};

/**
 * Human-readable messages for the most common PostgreSQL error codes.
 */
export const postgresHumanMessages: Record<string, string> = {
  '23502': 'A required field is missing. Please provide all required values.',
  '23503': 'This record references a related item that does not exist.',
  '23505': 'A record with this value already exists. Please use a unique value.',
  '23514': 'The provided value does not meet the required constraints.',
  '08000': 'Could not connect to the database. Please check your connection settings.',
  '08006': 'The database connection was lost. Please try again.',
  '53300': 'The database has too many connections. Please try again later.',
  '57014': 'The database query was cancelled. Please try again.',
  '40001': 'A database conflict occurred. Please retry your request.',
  '40P01': 'A database deadlock was detected. Please retry your request.',
  '42601': 'There is a syntax error in the database query.',
  '42P01': 'The requested database table does not exist.',
  P0001: 'The database raised an application error.',
  P0002: 'No matching record was found.',
};
